scrape_configs:
    - job_name: 'prometheus'
      scrape_interval: 30s
      scrape_timeout: 30s
  
      static_configs:
        - targets: ['192.168.10.112:8080']
          labels:
            service: 'test-harness'
            group: 'dev'