{
 "title": "Test Harness Dashboard",
 "time": { "from": "2020-05-21T05:34:00.084Z", "to": "2020-05-21T05:49:37.398Z" },
 "panels": [
  { "title": "Transaction stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Transactions status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sent_transactions" },
    { "expr": "successTx" },
    {}
   ]
  },
  {
   "title": "Unfinalised TX",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "unfinalised_transactions" }
   ]
  },
  {
   "title": "Finalisation duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(tx_process_duration_ms_bucket[5m])) by (le))"
    }
   ]
  },
  { "title": "Application stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Process CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[5m])",
     "legendFormat": "Process_cpu"
    }
   ]
  },
  {
   "title": "Events loop",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nodejs_eventloop_lag_seconds" }
   ]
  },
  {
   "title": "Heap space size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nodejs_heap_space_size_available_bytes"
    }
   ]
  }
 ]
}